
PREFIXES = {
    'bibo': 'http://purl.org/ontology/bibo/',
    'dbpedia': 'http://dbpedia.org/resource/',
    'dbpedia-owl': 'http://dbpedia.org/ontology/',
    'dce': 'http://purl.org/dc/elements/1.1/',
    'dcterms': 'http://purl.org/dc/terms/',
    'fabio': 'http://purl.org/spar/fabio/',
    'foaf': 'http://xmlns.com/foaf/0.1/',
    'geo': 'http://www.w3.org/2003/01/geo/wgs84_pos#',
    'gndo': 'http://d-nb.info/standards/elementset/gnd#',
    'gvp': 'http://vocab.getty.edu/ontology#',
    'lemon': 'http://lemon-model.net/lemon#',
    'locah': 'http://data.archiveshub.ac.uk/def/',
    'mrel': 'http://www.loc.gov/vocabulary/relators/',
    'owl': 'https://www.w3.org/2002/07/owl/',
    'pext': 'http://www.ontotext.com/proton/protonext.html#',
    'place': 'http://purl.org/ontology/places#',
    'rdf': 'https://www.w3.org/1999/02/22-rdf-syntax-ns#',
    'te': 'http://www.w3.org/2006/time-entry#',
    'umbel': 'http://umbel.org/umbel#',
    'utpl_geo': 'http://geo.dbpedia.utpl.edu.ec/resource/',
    'vgo': 'http://purl.org/net/VideoGameOntology#',
}
